// Generated by scripts/gen-clients.ts from schema/canvas-api.json. Do not edit.

export const SCHEMA_VERSION = 1;

/** Prefixed id, e.g. obj_01H…, men_… */
export type Id = string;

export type Frame = {
  x: number;
  y: number;
  w: number;
  h: number;
};

export type Actor = {
  kind: "user";
} | {
  kind: "agent";
  tile: Id;
  agent?: string;
};

/** 1-based inclusive line range */
export type LineRange = {
  start: number;
  end: number;
};

export type Lifecycle = {
  state: "working" | "blocked" | "idle" | "done" | "unknown";
  message?: string;
  seen?: boolean;
};

export type TerminalProps = {
  cwd: string;
  /** argv run inside the zmx session */
  command: string[];
  zmxSession?: string;
  title?: string;
  agent?: {
    kind: string;
    sessionId?: string;
    sessionPath?: string;
  };
  lifecycle?: Lifecycle;
};

export type BrowserProps = {
  url: string;
  title?: string;
};

export type CodeProps = {
  /** path relative to the board root */
  path: string;
  /** lines to scroll to and tint; the tile always shows the whole file */
  range?: LineRange;
  symbol?: string;
  /** one-line subtitle under the tile's header (plain text, `inline code` allowed); truncated, never wraps */
  caption?: string;
  /** gutter signs show changes against this: merge-base | head | <sha> */
  diffBase?: string;
  /** terminal tile this follow tile tracks */
  followOf?: Id;
  /** follow tiles: what the agent last did at this location */
  lastAction?: "read" | "edit" | "write" | "lsp" | "search";
  /** follow tiles: recent locations, newest first, without repeats */
  history?: ({
    path: string;
    range?: LineRange;
    action: "read" | "edit" | "write" | "lsp" | "search";
  })[];
  pinnedCommit?: string;
};

export type NoteProps = {
  /** Markdown. Code fence info strings pick a mode: ```ts file=path#L10-40``` (or symbol=Name, optionally with file=) is a live excerpt of the file; add `propose` to render the fence body as a diff against that range; file=path@<sha>#L10-40 pins to a commit; anchor="first line text" re-finds the range when lines move. Any other fence is free-written; path:line references in it are clickable. */
  markdown: string;
};

export type HtmlProps = {
  /** page body (or a full document); the kit (Tailwind, Mermaid, canvas-code/link/decisions/compare) is preloaded */
  html: string;
  title?: string;
  allowNetwork?: string[];
  /** tile state written by the page through its channel (e.g. canvas-decisions choices by key); at most 256 KiB */
  state?: Record<string, unknown>;
};

export type ShapeProps = {
  kind: "rect" | "ellipse" | "text" | "ink";
  text?: string;
  /** ink points [x, y, pressure?] in object-local coordinates */
  points?: number[][];
  /** palette name (black, grey, blue, green, orange, red, violet) or #rrggbb */
  color?: string;
  /** rect/ellipse interior; only filled interiors hit-test, so an unfilled shape never blocks what is beneath it */
  fill?: "none" | "semi" | "solid";
};

export type Binding = {
  object: Id;
  lines?: LineRange;
  selector?: string;
} | {
  point: number[];
};

export type ArrowProps = {
  from: Binding;
  to: Binding;
  /** semantic edge type, e.g. hypothesis_about, calls, depends_on */
  relation?: string;
  label?: string;
  /** palette name or #rrggbb, as ShapeProps.color */
  color?: string;
  /** straight: one segment between the facing sides; orthogonal: horizontal/vertical segments with one jog; avoid: horizontal/vertical segments around every tile (and text or filled shape) in the way. Arrows between the same two objects (either direction) are drawn apart automatically; labels sit beside the route, clear of boxes where possible. */
  route?: "straight" | "orthogonal" | "avoid";
};

/** A group is a region: its frame is always its members' bounds plus `padding`, with a 32 pt title band on top, kept current as members move, resize, or go away (a `frame` passed for a group is ignored). `object.get --as graph` encloses what lies inside that frame. */
export type GroupProps = {
  members: Id[];
  /** shown in the title band; the band is the group's drag handle */
  title?: string;
  /** palette name or #rrggbb, as ShapeProps.color; tints the region and title */
  color?: string;
  /** space between the members' bounds and the region's edge */
  padding?: number;
};

/** with size: fit, where the object goes; the rest of its frame is measured */
export type FitFrame = {
  x: number;
  y: number;
  /** wrap width for notes and text; for code the widest the tile may get (default 960), past which long lines wrap */
  w?: number;
};

export type Size = {
  w: number;
  h: number;
};

export type ObjectType = "terminal" | "browser" | "code" | "note" | "html" | "shape" | "arrow" | "group";

export type CanvasObject = {
  id: Id;
  type: ObjectType;
  frame: Frame;
  z: number;
  rev: number;
  parent?: Id;
  createdBy: Actor;
  updatedBy?: Actor;
  createdAt: string;
  updatedAt: string;
  /** one of TerminalProps | BrowserProps | CodeProps | NoteProps | HtmlProps | ShapeProps | ArrowProps | GroupProps, selected by type */
  props: Record<string, unknown>;
};

export type MentionTarget = {
  kind: "object";
  object: Id;
} | {
  kind: "code";
  object: Id;
  path: string;
  lines: LineRange;
  /** diff side of the lines; absent outside a diff */
  side?: "old" | "new";
  symbol?: string;
  /** with side old or absent: the commit whose version of path holds the lines (deleted diff rows, pinned excerpts); with side new: the diff base. Absent: the working tree */
  commit?: string;
} | {
  kind: "dom";
  object: Id;
  url: string;
  selector: string;
  text?: string;
} | {
  kind: "terminal";
  object: Id;
  text: string;
} | {
  kind: "group";
  objects: Id[];
  name?: string;
};

export type Mention = {
  id: Id;
  target: MentionTarget;
  label: string;
  stagedAt: string;
  /** target changed since staging */
  edited: boolean;
};

export type ResolvedMention = {
  /** mention id, for tray.commit */
  id: Id;
  /** stable reference, e.g. canvas:men_12@rev3 */
  ref: string;
  label: string;
  /** compact text for prompt context: location, excerpt, relations */
  summary: string;
  /** structured view: contents, encloses, overlaps, arrows */
  graph?: Record<string, unknown>;
};

export type Agent = {
  tile: Id;
  board?: Id;
  name?: string;
  kind: string;
  sessionId?: string;
  lifecycle: Lifecycle;
};

export type BoardInfo = {
  board: Id;
  /** root directory the board was last opened at */
  root: string;
  /** the root directory no longer exists (e.g. a deleted worktree); the board is kept */
  archived: boolean;
  /** the board has a window in the app (only open boards accept `board` params) */
  open: boolean;
  /** ISO 8601 time the board was last saved; absent for a board never saved */
  updatedAt?: string;
  /** object count */
  objects: number;
};

/** What the board's window shows: `rect` is the visible canvas area in canvas coordinates, `zoom` the magnification (1 = 100%, one point per canvas unit). */
export type Viewport = {
  rect: Frame;
  zoom: number;
};

/** Where an object landed in a rendered image and whether its content really painted. */
export type RenderedObject = {
  id: Id;
  type: ObjectType;
  /** image pixels, top-left origin; a tile's rect includes its 26 pt title bar */
  pixelRect: Frame;
  /** placeholder: content not loaded in time or not renderable (a stand-in was drawn); failed: rendering errored */
  state: "rendered" | "placeholder" | "failed";
  /** why a tile is a placeholder or failed */
  reason?: string;
  /** the content's own extent in points at the tile's width (tiles only) */
  contentSize?: {
    w?: number;
    h?: number;
  };
  /** points of content beyond the frame (right, bottom); absent when it fits */
  overflow?: {
    x?: number;
    y?: number;
  };
};

export type HistoryEntry = {
  /** log cursor; pass the largest seen as `since` */
  seq: number;
  /** board revision right after the entry (viewport/selection entries don't change it) */
  rev: number;
  /** ISO 8601 time */
  at: string;
  /** `user`, `system`, or `agent:<terminal tile id>` */
  actor: string;
  kind: "created" | "updated" | "deleted" | "viewport" | "selection" | "follow" | "restart";
  /** the object (for follow: the follow tile) */
  id?: Id;
  type?: ObjectType;
  /** one human-readable line */
  summary: string;
  viewport?: Viewport;
  selection?: Id[];
};

export type SystemPingParams = Record<string, unknown>;
export type SystemPingResult = {
  version: number;
  app?: string;
};

export type BoardGetParams = {
  board?: Id;
  /** board revision cursor from a previous call */
  since?: number;
};
export type BoardGetResult = {
  board: Id;
  root: string;
  revision: number;
  objects: CanvasObject[];
  changed?: Id[];
};

export type BoardHistoryParams = {
  board?: Id;
  /** entries after this `seq` cursor, or after this ISO 8601 time */
  since?: number | string;
  /** newest entries returned when more match */
  limit?: number;
  /** only these kinds */
  kinds?: ("created" | "updated" | "deleted" | "viewport" | "selection" | "follow" | "restart")[];
};
export type BoardHistoryResult = {
  board: Id;
  /** newest `seq` in the log */
  cursor: number;
  /** oldest first */
  entries: HistoryEntry[];
  /** more entries matched than `limit`, or the ring buffer already dropped some after `since` */
  truncated: boolean;
  /** `since` is newer than this log: the app restarted, so every entry is returned */
  restarted: boolean;
};

export type BoardListParams = Record<string, unknown>;
export type BoardListResult = {
  boards: BoardInfo[];
};

export type BoardOpenParams = {
  /** absolute directory path (`~` allowed); one board per directory */
  root: string;
  /** bring the board's tab to the front */
  select?: boolean;
};
export type BoardOpenResult = {
  board: Id;
  root: string;
  objects: number;
};

export type BoardExportParams = {
  board?: Id;
  /** absolute, or relative to the board root; default .canvas/board.json */
  path?: string;
};
export type BoardExportResult = {
  /** absolute path written */
  path: string;
  objects: number;
};

export type ObjectGetParams = {
  id: Id;
  as?: "raw" | "graph";
};
export type ObjectGetResult = {
  object: CanvasObject;
  graph?: Record<string, unknown>;
};

export type ObjectCreateParams = {
  board?: Id;
  type: ObjectType;
  props: Record<string, unknown>;
  frame?: Frame | FitFrame;
  /** measure the frame's size from the content; `frame` then only needs x, y (and w to wrap a note or text, or to cap a code tile's width) */
  size?: "fit";
  parent?: Id;
  /** calling tile id; clients fill from CANVAS_TILE_ID */
  caller?: Id;
};
export type ObjectCreateResult = {
  object: CanvasObject;
};

export type ObjectUpdateParams = {
  id: Id;
  rev?: number;
  frame?: Frame | FitFrame;
  /** measure the frame's size from the content */
  size?: "fit";
  props?: Record<string, unknown>;
  caller?: Id;
};
export type ObjectUpdateResult = {
  object: CanvasObject;
};

export type ObjectDeleteParams = {
  id: Id;
  caller?: Id;
};
export type ObjectDeleteResult = Record<string, unknown>;

export type ObjectMeasureParams = {
  board?: Id;
  type: ObjectType;
  props: Record<string, unknown>;
  /** wrap width for notes and text; maximum width for code (default 960) */
  width?: number;
  caller?: Id;
};
export type ObjectMeasureResult = Size;

export type ObjectBatchParams = {
  board?: Id;
  ops: ({
    method: "object.create" | "object.update" | "object.delete" | "layout.place" | "layout.stack";
    params: Record<string, unknown>;
  })[];
  caller?: Id;
};
export type ObjectBatchResult = {
  /** each op's result, in order */
  results: unknown[];
  revision: number;
};

export type LayoutPlaceParams = {
  id: Id;
  near: Id;
  side?: "right" | "left" | "above" | "below";
  gap?: number;
  /** along the side: start lines up top (or left) edges, end bottom (or right) edges */
  align?: "start" | "center" | "end";
  caller?: Id;
};
export type LayoutPlaceResult = {
  frames: Record<string, unknown>;
};

export type LayoutStackParams = {
  ids: Id[];
  direction?: "row" | "column";
  gap?: number;
  /** maximum line length in points */
  wrapAt?: number;
  /** across the line: rows align tops (start), middles, or bottoms */
  align?: "start" | "center" | "end";
  origin?: {
    x: number;
    y: number;
  };
  caller?: Id;
};
export type LayoutStackResult = {
  frames: Record<string, unknown>;
};

export type LayoutCheckParams = {
  board?: Id;
  ids?: Id[];
  rect?: Frame;
  caller?: Id;
};
export type LayoutCheckResult = {
  overlaps: Id[][];
  arrowCrossings: {
    arrow: Id;
    crosses: Id[];
  }[];
  overflow: {
    id: Id;
    x: number;
    y: number;
  }[];
};

export type TrayListParams = {
  board?: Id;
};
export type TrayListResult = {
  mentions: Mention[];
};

export type TrayStageParams = {
  target: MentionTarget;
  board?: Id;
};
export type TrayStageResult = {
  mention: Mention;
};

export type TrayUnstageParams = {
  id: Id;
};
export type TrayUnstageResult = Record<string, unknown>;

export type TrayDrainParams = {
  board?: Id;
  caller?: Id;
  peek?: boolean;
};
export type TrayDrainResult = {
  mentions: ResolvedMention[];
  /** ready-to-inject prompt context block; empty string when the tray was empty */
  context: string;
};

export type TrayCommitParams = {
  board?: Id;
  ids: Id[];
};
export type TrayCommitResult = Record<string, unknown>;

export type AgentReportParams = {
  tile: Id;
  kind: string;
  state: "working" | "blocked" | "idle" | "unknown";
  message?: string;
  seq?: number;
  source?: string;
};
export type AgentReportResult = Record<string, unknown>;

export type AgentReportSessionParams = {
  tile: Id;
  kind: string;
  sessionId?: string;
  sessionPath?: string;
};
export type AgentReportSessionResult = Record<string, unknown>;

export type AgentReleaseParams = {
  tile: Id;
  kind: string;
  source?: string;
};
export type AgentReleaseResult = Record<string, unknown>;

export type AgentListParams = Record<string, unknown>;
export type AgentListResult = {
  agents: Agent[];
};

export type AgentPromptParams = {
  /** agent name or tile id */
  target: string;
  text: string;
};
export type AgentPromptResult = {
  agent: Agent;
};

export type AgentWaitParams = {
  target: string;
  until?: ("working" | "blocked" | "idle" | "done" | "unknown")[];
  timeoutMs?: number;
};
export type AgentWaitResult = {
  agent: Agent;
};

export type AgentReadParams = {
  /** agent name or tile id */
  target: string;
  /** tail length; larger values are capped at 2000 */
  lines?: number;
};
export type AgentReadResult = {
  agent: Agent;
  text: string;
  /** number of lines returned */
  lines: number;
};

export type FollowReportParams = {
  tile: Id;
  /** absolute path or path relative to the board root */
  path: string;
  range?: LineRange;
  action: "read" | "edit" | "write" | "lsp" | "search";
};
export type FollowReportResult = Record<string, unknown>;

export type ViewAttentionParams = {
  id: Id;
  message?: string;
  /** remove this object's marker instead of raising it */
  clear?: boolean;
};
export type ViewAttentionResult = {
  /** the marked object (markers are keyed by object) */
  id: Id;
  /** a marker is showing after this call */
  active: boolean;
};

export type ViewGetParams = {
  board?: Id;
};
export type ViewGetResult = {
  board: Id;
  viewport: Viewport;
  /** terminal that receives the tray and dictation */
  promptTarget?: Id;
  /** tile holding keyboard focus */
  focused?: Id;
  selection: Id[];
  enteredGroup?: Id;
  /** the window is at least partly visible on a displayed Space */
  visible: boolean;
};

export type ViewRenderParams = {
  board?: Id;
  target: Id | Id[] | Frame;
  /** pixels per canvas point; lowered to keep the image under 32 megapixels (the result says what was used) */
  scale?: number;
  /** id targets: render the whole content, not just the part inside the frame */
  full?: boolean;
  /** object types to leave out (e.g. ["terminal"]) */
  exclude?: ObjectType[];
  /** canvas points added around the target */
  padding?: number;
  /** absolute path to write; format from the extension (.png, .jpg/.jpeg). Clients resolve relative paths */
  out?: string;
  /** inline format when no `out` is given */
  format?: "png" | "jpeg";
  /** how long to wait for content (HTML pages, file reads) before drawing placeholders */
  timeoutMs?: number;
};
export type ViewRenderResult = {
  /** absolute path written (when `out` was given) */
  path?: string;
  /** encoded image (when no `out` was given) */
  imageBase64?: string;
  format: "png" | "jpeg";
  /** pixels */
  width: number;
  /** pixels */
  height: number;
  /** canvas area the image covers: pixel (px, py) = canvas (x + px / scale, y + py / scale) */
  canvasRect: Frame;
  /** pixels per canvas point actually used */
  scale: number;
  /** every object drawn, bottom to top */
  objects: RenderedObject[];
};

export type ViewSnapshotParams = {
  board?: Id;
  /** absolute path to write; format from the extension (.png, .jpg/.jpeg). Clients resolve relative paths */
  out?: string;
  /** inline format when no `out` is given */
  format?: "png" | "jpeg";
};
export type ViewSnapshotResult = {
  /** absolute path written (when `out` was given) */
  path?: string;
  /** encoded image (when no `out` was given) */
  imageBase64?: string;
  format: "png" | "jpeg";
  /** pixels */
  width: number;
  /** pixels */
  height: number;
  viewport: Viewport;
  /** image pixels per canvas point (backing scale × zoom); the canvas fills the image from its top-left: pixel (px, py) = canvas (viewport.rect.x + px / scale, viewport.rect.y + py / scale) */
  scale: number;
  /** objects at least partly visible, bottom to top (state is always rendered) */
  objects: RenderedObject[];
};

export type EventsSubscribeParams = {
  board?: Id;
  events?: string[];
};
export type EventsSubscribeResult = Record<string, unknown>;

/** Every API method, grouped by namespace (`api.board.get(...)`). */
export interface CanvasApi {
  system: {
    /** Liveness and schema version. */
    ping(params?: SystemPingParams): Promise<SystemPingResult>;
  };
  board: {
    /** Board manifest: all objects (props summarized for heavy types) plus a change cursor. Objects created or changed since `since` are flagged. */
    get(params?: BoardGetParams): Promise<BoardGetResult>;
    /** Activity log: who created, changed, or deleted what (including objects that existed only for seconds), where the user's viewport settled, what they selected, follow-tile re-aims, and app starts. Plain request/response, cheap to poll: pass the returned `cursor` as `since` next time. In memory, newest 2000 entries per board; an app restart starts a new log with a `restart` entry. */
    history(params?: BoardHistoryParams): Promise<BoardHistoryResult>;
    /** Every stored board, open or not, including archived boards whose root directory is gone. */
    list(params?: BoardListParams): Promise<BoardListResult>;
    /** Open the board for a directory (creating it if new) as a tab of the frontmost board window. The user's current tab stays in front unless `select` is true. Opening an already-open board only selects it when `select` is true. */
    open(params: BoardOpenParams): Promise<BoardOpenResult>;
    /** Write a pretty-printed JSON snapshot of an open board (objects, frames, props; not the personal selection tray) into the repo. Committing it is left to the caller. */
    export(params?: BoardExportParams): Promise<BoardExportResult>;
  };
  object: {
    /** Read one object. `as: graph` adds structural relations: encloses, enclosedBy, overlaps, arrowsIn/arrowsOut (arrows bound to it), arrows (arrows drawn inside it, with from/to bindings), and from/to for an arrow. To look at an object, `view.render` it. */
    get(params: ObjectGetParams): Promise<ObjectGetResult>;
    /** Create an object. Omit `frame` to let the canvas place it next to the calling agent's terminal (or the viewport center for users). `size: fit` sizes the frame to the content (object.measure; notes and text wrap at `frame.w`; code is at most `frame.w` wide, default 960, and wraps longer lines). The caller's tile (CANVAS_TILE_ID) becomes createdBy. */
    create(params: ObjectCreateParams): Promise<ObjectCreateResult>;
    /** Patch an object's frame and/or props (shallow merge). Pass `rev` for optimistic concurrency. `size: fit` re-measures the frame from the (patched) content at its current position and width (code: at most `frame.w`, default 960, never its current width), or at `frame` x, y, w. */
    update(params: ObjectUpdateParams): Promise<ObjectUpdateResult>;
    /** Delete an object (and remove it from any staged mentions). Arrows bound to it keep their drawn route: that end becomes a free `point` where it last attached. */
    delete(params: ObjectDeleteParams): Promise<ObjectDeleteResult>;
    /** Intrinsic size: the whole frame (tile title bar included) that shows the content without scrolling. code: exactly `range` (or the symbol, or the whole file), as wide as its longest line up to `width` (default 960) with longer lines soft-wrapped and counted in the height, with the caption strip when `caption` is set; note: the rendered markdown (live fences resolved) at `width` (default 280); shape: text at `width` (default one unwrapped line per paragraph), rect/ellipse around their text. Other types are `unsupported`. */
    measure(params: ObjectMeasureParams): Promise<ObjectMeasureResult>;
    /** Apply several changes atomically: one board revision and one undo step, and if any op fails nothing changes (the error names the op). Ops are object.create/update/delete and layout.place/stack with their usual params; the string "$n" anywhere in an op's params stands for the id created by op n (e.g. an arrow from "$0" to "$1", a group with members ["$0", "$1"]). */
    batch(params: ObjectBatchParams): Promise<ObjectBatchResult>;
  };
  layout: {
    /** Move an object `gap` points beside another (one undo step). Groups move their members; arrows follow their bound ends. */
    place(params: LayoutPlaceParams): Promise<LayoutPlaceResult>;
    /** Lay objects out in a row (left to right) or column (top to bottom), `gap` apart, starting where the first one is or at `origin` (one undo step). With `wrapAt`, a line longer than that many points wraps into a new line. Groups move as a whole, so stacking groups lays out lanes. */
    stack(params: LayoutStackParams): Promise<LayoutStackResult>;
    /** Layout problems for `ids`, for what intersects `rect`, or for the whole board: overlapping objects (a group and its members, and an unfilled rect/ellipse around what it contains, don't count), arrows whose route runs through tiles, text, or filled shapes other than their own ends, and code/note/text whose content doesn't fit its frame (points missing in x and y). */
    check(params?: LayoutCheckParams): Promise<LayoutCheckResult>;
  };
  tray: {
    /** Staged mentions, in staging order. */
    list(params?: TrayListParams): Promise<TrayListResult>;
    /** Stage a mention (normally done by the user with Hyper-click; exposed for tests and agents). */
    stage(params: TrayStageParams): Promise<TrayStageResult>;
    /** Remove one staged mention. */
    unstage(params: TrayUnstageParams): Promise<TrayUnstageResult>;
    /** Resolve all staged mentions at their current revision and return them with a ready-to-inject context block. By default the tray is cleared; with `peek: true` it is left intact so the caller can `tray.commit` exactly these ids once the context has really been delivered (a cancelled prompt then loses nothing). */
    drain(params?: TrayDrainParams): Promise<TrayDrainResult>;
    /** Remove exactly these mentions from the tray after their context was delivered (second half of a `peek` drain). Unknown ids are ignored. */
    commit(params: TrayCommitParams): Promise<TrayCommitResult>;
  };
  agent: {
    /** Report lifecycle state for the agent running in a terminal tile. Stale `seq` values from the same source are ignored. */
    report(params: AgentReportParams): Promise<AgentReportResult>;
    /** Report the agent's native session identity so the tile can resume it after a reboot. */
    report_session(params: AgentReportSessionParams): Promise<AgentReportSessionResult>;
    /** The agent in this tile exited; clear its lifecycle authority. */
    release(params: AgentReleaseParams): Promise<AgentReleaseResult>;
    /** Agents across all open boards. */
    list(params?: AgentListParams): Promise<AgentListResult>;
    /** Paste a prompt into another agent's terminal (bracketed paste) and press Enter. Rejected with `conflict` if that agent is blocked. */
    prompt(params: AgentPromptParams): Promise<AgentPromptResult>;
    /** Wait until the target agent reaches one of the given states. */
    wait(params: AgentWaitParams): Promise<AgentWaitResult>;
    /** Recent text of an agent's terminal: the tail of its zmx session scrollback as plain text (what the screen shows plus history), trailing blank lines removed. */
    read(params: AgentReadParams): Promise<AgentReadResult>;
  };
  follow: {
    /** Report a file location an agent just read, edited, or wrote; re-aims that terminal's follow tile (unless the user is working in it, which holds re-aims for ~10 s). Files outside the board root and the terminal's cwd are ignored. */
    report(params: FollowReportParams): Promise<FollowReportResult>;
  };
  view: {
    /** Raise an attention marker pointing at an object (one per object; raising again replaces its message), or remove it with `clear: true`. The user seeing the object also clears it. Never moves the user's viewport. */
    attention(params: ViewAttentionParams): Promise<ViewAttentionResult>;
    /** What the user is looking at right now, without pixels: the visible canvas rect and zoom, the prompt-target terminal, the tile with keyboard focus, the selection, and whether the window is visible on screen. */
    get(params?: ViewGetParams): Promise<ViewGetResult>;
    /** Render part of the board offscreen at a fixed scale, independent of the user's viewport (never moves it). `target` is an object id, a list of ids, or a canvas rect; ids render the canvas region under their outlines (with whatever overlaps them), `full` draws those tiles' whole content (note/HTML/code scroll height; code wraps at its tile's width) extending below/right of their frames. Waits until content has painted (up to `timeoutMs`) and reports per-object state instead of returning blanks. App chrome (toolbar, tray, hints, selection rings, attention markers) is never drawn. */
    render(params: ViewRenderParams): Promise<ViewRenderResult>;
    /** The board's window as the user sees it right now (viewport, tiles, toolbar, tray), with the viewport it shows. Terminal tiles are drawn from their session text. To look at something regardless of where the user is, use view.render. */
    snapshot(params?: ViewSnapshotParams): Promise<ViewSnapshotResult>;
  };
  events: {
    /** Turn this connection into an event stream. Events: object.created, object.updated, object.deleted, tray.changed, agent.lifecycle, follow.updated. */
    subscribe(params?: EventsSubscribeParams): Promise<EventsSubscribeResult>;
  };
}

/** Params a client fills from its tile (`caller`) and board when the call omits them, with the env var each defaults from. */
export const ENV_DEFAULTS: Record<string, string> = {"caller":"CANVAS_TILE_ID","board":"CANVAS_BOARD_ID"};

/** `call` receives the method's auto-filled param names (keys of ENV_DEFAULTS it accepts). */
export function bindMethods(call: (method: string, params: object, envKeys: string[]) => Promise<unknown>): CanvasApi {
  return {
    system: {
      ping: (params?: SystemPingParams) => call("system.ping", params ?? {}, []) as Promise<SystemPingResult>,
    },
    board: {
      get: (params?: BoardGetParams) => call("board.get", params ?? {}, ["board"]) as Promise<BoardGetResult>,
      history: (params?: BoardHistoryParams) => call("board.history", params ?? {}, ["board"]) as Promise<BoardHistoryResult>,
      list: (params?: BoardListParams) => call("board.list", params ?? {}, []) as Promise<BoardListResult>,
      open: (params: BoardOpenParams) => call("board.open", params ?? {}, []) as Promise<BoardOpenResult>,
      export: (params?: BoardExportParams) => call("board.export", params ?? {}, ["board"]) as Promise<BoardExportResult>,
    },
    object: {
      get: (params: ObjectGetParams) => call("object.get", params ?? {}, []) as Promise<ObjectGetResult>,
      create: (params: ObjectCreateParams) => call("object.create", params ?? {}, ["board","caller"]) as Promise<ObjectCreateResult>,
      update: (params: ObjectUpdateParams) => call("object.update", params ?? {}, ["caller"]) as Promise<ObjectUpdateResult>,
      delete: (params: ObjectDeleteParams) => call("object.delete", params ?? {}, ["caller"]) as Promise<ObjectDeleteResult>,
      measure: (params: ObjectMeasureParams) => call("object.measure", params ?? {}, ["board","caller"]) as Promise<ObjectMeasureResult>,
      batch: (params: ObjectBatchParams) => call("object.batch", params ?? {}, ["board","caller"]) as Promise<ObjectBatchResult>,
    },
    layout: {
      place: (params: LayoutPlaceParams) => call("layout.place", params ?? {}, ["caller"]) as Promise<LayoutPlaceResult>,
      stack: (params: LayoutStackParams) => call("layout.stack", params ?? {}, ["caller"]) as Promise<LayoutStackResult>,
      check: (params?: LayoutCheckParams) => call("layout.check", params ?? {}, ["board","caller"]) as Promise<LayoutCheckResult>,
    },
    tray: {
      list: (params?: TrayListParams) => call("tray.list", params ?? {}, ["board"]) as Promise<TrayListResult>,
      stage: (params: TrayStageParams) => call("tray.stage", params ?? {}, ["board"]) as Promise<TrayStageResult>,
      unstage: (params: TrayUnstageParams) => call("tray.unstage", params ?? {}, []) as Promise<TrayUnstageResult>,
      drain: (params?: TrayDrainParams) => call("tray.drain", params ?? {}, ["board","caller"]) as Promise<TrayDrainResult>,
      commit: (params: TrayCommitParams) => call("tray.commit", params ?? {}, ["board"]) as Promise<TrayCommitResult>,
    },
    agent: {
      report: (params: AgentReportParams) => call("agent.report", params ?? {}, []) as Promise<AgentReportResult>,
      report_session: (params: AgentReportSessionParams) => call("agent.report_session", params ?? {}, []) as Promise<AgentReportSessionResult>,
      release: (params: AgentReleaseParams) => call("agent.release", params ?? {}, []) as Promise<AgentReleaseResult>,
      list: (params?: AgentListParams) => call("agent.list", params ?? {}, []) as Promise<AgentListResult>,
      prompt: (params: AgentPromptParams) => call("agent.prompt", params ?? {}, []) as Promise<AgentPromptResult>,
      wait: (params: AgentWaitParams) => call("agent.wait", params ?? {}, []) as Promise<AgentWaitResult>,
      read: (params: AgentReadParams) => call("agent.read", params ?? {}, []) as Promise<AgentReadResult>,
    },
    follow: {
      report: (params: FollowReportParams) => call("follow.report", params ?? {}, []) as Promise<FollowReportResult>,
    },
    view: {
      attention: (params: ViewAttentionParams) => call("view.attention", params ?? {}, []) as Promise<ViewAttentionResult>,
      get: (params?: ViewGetParams) => call("view.get", params ?? {}, ["board"]) as Promise<ViewGetResult>,
      render: (params: ViewRenderParams) => call("view.render", params ?? {}, ["board"]) as Promise<ViewRenderResult>,
      snapshot: (params?: ViewSnapshotParams) => call("view.snapshot", params ?? {}, ["board"]) as Promise<ViewSnapshotResult>,
    },
    events: {
      subscribe: (params?: EventsSubscribeParams) => call("events.subscribe", params ?? {}, ["board"]) as Promise<EventsSubscribeResult>,
    },
  };
}

export const METHODS = ["system.ping","board.get","board.history","board.list","board.open","board.export","object.get","object.create","object.update","object.delete","object.measure","object.batch","layout.place","layout.stack","layout.check","tray.list","tray.stage","tray.unstage","tray.drain","tray.commit","agent.report","agent.report_session","agent.release","agent.list","agent.prompt","agent.wait","agent.read","follow.report","view.attention","view.get","view.render","view.snapshot","events.subscribe"] as const;
