// Generated by scripts/gen-clients.ts from schema/canvas-api.json. Do not edit.

export const SCHEMA_VERSION = 1;

/** Prefixed id, e.g. obj_01H…, men_… */
export type Id = string;

export type Frame = {
  x: number;
  y: number;
  w: number;
  h: number;
};

export type Actor = {
  kind: "user";
} | {
  kind: "agent";
  tile: Id;
  agent?: string;
};

/** 1-based inclusive line range */
export type LineRange = {
  start: number;
  end: number;
};

export type Lifecycle = {
  state: "working" | "blocked" | "idle" | "done" | "unknown";
  message?: string;
  seen?: boolean;
};

export type TerminalProps = {
  cwd: string;
  /** argv run inside the zmx session */
  command: string[];
  zmxSession?: string;
  title?: string;
  agent?: {
    kind: string;
    sessionId?: string;
    sessionPath?: string;
  };
  lifecycle?: Lifecycle;
};

export type BrowserProps = {
  url: string;
  title?: string;
};

export type CodeProps = {
  /** path relative to the board root */
  path: string;
  range?: LineRange;
  symbol?: string;
  mode?: "diff" | "source";
  /** merge-base | head | <sha> */
  diffBase?: string;
  /** terminal tile this follow tile tracks */
  followOf?: Id;
  /** follow tiles: what the agent last did at this location */
  lastAction?: "read" | "edit" | "lsp" | "search";
  /** follow tiles: recent locations, newest first, without repeats */
  history?: ({
    path: string;
    range?: LineRange;
    action: "read" | "edit" | "lsp" | "search";
  })[];
  pinnedCommit?: string;
};

export type NoteProps = {
  /** Markdown. Code fence info strings pick a mode: ```ts file=path#L10-40``` (or symbol=Name, optionally with file=) is a live excerpt of the file; add `propose` to render the fence body as a diff against that range; file=path@<sha>#L10-40 pins to a commit; anchor="first line text" re-finds the range when lines move. Any other fence is free-written; path:line references in it are clickable. */
  markdown: string;
};

export type HtmlProps = {
  /** page body (or a full document); the kit (Tailwind, Mermaid, canvas-code/link/decisions/compare) is preloaded */
  html: string;
  title?: string;
  allowNetwork?: string[];
  /** tile state written by the page through its channel (e.g. canvas-decisions choices by key); at most 256 KiB */
  state?: Record<string, unknown>;
};

export type ShapeProps = {
  kind: "rect" | "ellipse" | "text" | "ink";
  text?: string;
  /** ink points [x, y, pressure?] in object-local coordinates */
  points?: number[][];
  /** palette name (black, grey, blue, green, orange, red, violet) or #rrggbb */
  color?: string;
  /** rect/ellipse interior; only filled interiors hit-test, so an unfilled shape never blocks what is beneath it */
  fill?: "none" | "semi" | "solid";
};

export type Binding = {
  object: Id;
  lines?: LineRange;
  selector?: string;
} | {
  point: number[];
};

export type ArrowProps = {
  from: Binding;
  to: Binding;
  /** semantic edge type, e.g. hypothesis_about, calls, depends_on */
  relation?: string;
  label?: string;
  /** palette name or #rrggbb, as ShapeProps.color */
  color?: string;
};

export type GroupProps = {
  name?: string;
  members: Id[];
};

export type ObjectType = "terminal" | "browser" | "code" | "note" | "html" | "shape" | "arrow" | "group";

export type CanvasObject = {
  id: Id;
  type: ObjectType;
  frame: Frame;
  z: number;
  rev: number;
  parent?: Id;
  createdBy: Actor;
  updatedBy?: Actor;
  createdAt: string;
  updatedAt: string;
  /** one of TerminalProps | BrowserProps | CodeProps | NoteProps | HtmlProps | ShapeProps | ArrowProps | GroupProps, selected by type */
  props: Record<string, unknown>;
};

export type MentionTarget = {
  kind: "object";
  object: Id;
} | {
  kind: "code";
  object: Id;
  path: string;
  lines: LineRange;
  /** diff side of the lines; absent outside a diff */
  side?: "old" | "new";
  symbol?: string;
  /** with side old or absent: the commit whose version of path holds the lines (deleted diff rows, pinned excerpts); with side new: the diff base. Absent: the working tree */
  commit?: string;
} | {
  kind: "dom";
  object: Id;
  url: string;
  selector: string;
  text?: string;
} | {
  kind: "terminal";
  object: Id;
  text: string;
} | {
  kind: "group";
  objects: Id[];
  name?: string;
};

export type Mention = {
  id: Id;
  target: MentionTarget;
  label: string;
  stagedAt: string;
  /** target changed since staging */
  edited: boolean;
};

export type ResolvedMention = {
  /** mention id, for tray.commit */
  id: Id;
  /** stable reference, e.g. canvas:men_12@rev3 */
  ref: string;
  label: string;
  /** compact text for prompt context: location, excerpt, relations */
  summary: string;
  /** structured view: contents, encloses, overlaps, arrows */
  graph?: Record<string, unknown>;
};

export type Agent = {
  tile: Id;
  board?: Id;
  name?: string;
  kind: string;
  sessionId?: string;
  lifecycle: Lifecycle;
};

export type BoardInfo = {
  board: Id;
  /** root directory the board was last opened at */
  root: string;
  /** the root directory no longer exists (e.g. a deleted worktree); the board is kept */
  archived: boolean;
  /** the board has a window in the app (only open boards accept `board` params) */
  open: boolean;
  /** ISO 8601 time the board was last saved; absent for a board never saved */
  updatedAt?: string;
  /** object count */
  objects: number;
};

export type SystemPingParams = Record<string, unknown>;
export type SystemPingResult = {
  version: number;
  app?: string;
};

export type BoardGetParams = {
  board?: Id;
  /** board revision cursor from a previous call */
  since?: number;
};
export type BoardGetResult = {
  board: Id;
  root: string;
  revision: number;
  objects: CanvasObject[];
  changed?: Id[];
};

export type BoardListParams = Record<string, unknown>;
export type BoardListResult = {
  boards: BoardInfo[];
};

export type BoardExportParams = {
  board?: Id;
  /** absolute, or relative to the board root; default .canvas/board.json */
  path?: string;
};
export type BoardExportResult = {
  /** absolute path written */
  path: string;
  objects: number;
};

export type ObjectGetParams = {
  id: Id;
  as?: "raw" | "graph" | "image";
};
export type ObjectGetResult = {
  object: CanvasObject;
  graph?: Record<string, unknown>;
  pngBase64?: string;
};

export type ObjectCreateParams = {
  board?: Id;
  type: ObjectType;
  props: Record<string, unknown>;
  frame?: Frame;
  parent?: Id;
  /** calling tile id; clients fill from CANVAS_TILE_ID */
  caller?: Id;
};
export type ObjectCreateResult = {
  object: CanvasObject;
};

export type ObjectUpdateParams = {
  id: Id;
  rev?: number;
  frame?: Frame;
  props?: Record<string, unknown>;
  caller?: Id;
};
export type ObjectUpdateResult = {
  object: CanvasObject;
};

export type ObjectDeleteParams = {
  id: Id;
  caller?: Id;
};
export type ObjectDeleteResult = Record<string, unknown>;

export type TrayListParams = {
  board?: Id;
};
export type TrayListResult = {
  mentions: Mention[];
};

export type TrayStageParams = {
  target: MentionTarget;
  board?: Id;
};
export type TrayStageResult = {
  mention: Mention;
};

export type TrayUnstageParams = {
  id: Id;
};
export type TrayUnstageResult = Record<string, unknown>;

export type TrayDrainParams = {
  board?: Id;
  caller?: Id;
  peek?: boolean;
};
export type TrayDrainResult = {
  mentions: ResolvedMention[];
  /** ready-to-inject prompt context block; empty string when the tray was empty */
  context: string;
};

export type TrayCommitParams = {
  board?: Id;
  ids: Id[];
};
export type TrayCommitResult = Record<string, unknown>;

export type AgentReportParams = {
  tile: Id;
  kind: string;
  state: "working" | "blocked" | "idle" | "unknown";
  message?: string;
  seq?: number;
  source?: string;
};
export type AgentReportResult = Record<string, unknown>;

export type AgentReportSessionParams = {
  tile: Id;
  kind: string;
  sessionId?: string;
  sessionPath?: string;
};
export type AgentReportSessionResult = Record<string, unknown>;

export type AgentReleaseParams = {
  tile: Id;
  kind: string;
  source?: string;
};
export type AgentReleaseResult = Record<string, unknown>;

export type AgentListParams = Record<string, unknown>;
export type AgentListResult = {
  agents: Agent[];
};

export type AgentPromptParams = {
  /** agent name or tile id */
  target: string;
  text: string;
};
export type AgentPromptResult = {
  agent: Agent;
};

export type AgentWaitParams = {
  target: string;
  until?: ("working" | "blocked" | "idle" | "done" | "unknown")[];
  timeoutMs?: number;
};
export type AgentWaitResult = {
  agent: Agent;
};

export type AgentReadParams = {
  /** agent name or tile id */
  target: string;
  /** tail length; larger values are capped at 2000 */
  lines?: number;
};
export type AgentReadResult = {
  agent: Agent;
  text: string;
  /** number of lines returned */
  lines: number;
};

export type FollowReportParams = {
  tile: Id;
  /** absolute path or path relative to the board root */
  path: string;
  range?: LineRange;
  action: "read" | "edit" | "lsp" | "search";
};
export type FollowReportResult = Record<string, unknown>;

export type ViewAttentionParams = {
  id: Id;
  message?: string;
};
export type ViewAttentionResult = Record<string, unknown>;

export type ViewSnapshotParams = {
  board?: Id;
};
export type ViewSnapshotResult = {
  pngBase64: string;
  width: number;
  height: number;
};

export type EventsSubscribeParams = {
  board?: Id;
  events?: string[];
};
export type EventsSubscribeResult = Record<string, unknown>;

/** Every API method, grouped by namespace (`api.board.get(...)`). */
export interface CanvasApi {
  system: {
    /** Liveness and schema version. */
    ping(params?: SystemPingParams): Promise<SystemPingResult>;
  };
  board: {
    /** Board manifest: all objects (props summarized for heavy types) plus a change cursor. Objects created or changed since `since` are flagged. */
    get(params?: BoardGetParams): Promise<BoardGetResult>;
    /** Every stored board, open or not, including archived boards whose root directory is gone. */
    list(params?: BoardListParams): Promise<BoardListResult>;
    /** Write a pretty-printed JSON snapshot of an open board (objects, frames, props; not the personal selection tray) into the repo. Committing it is left to the caller. */
    export(params?: BoardExportParams): Promise<BoardExportResult>;
  };
  object: {
    /** Read one object. `as: graph` adds structural relations: encloses, enclosedBy, overlaps, arrowsIn/arrowsOut (arrows bound to it), arrows (arrows drawn inside it, with from/to bindings), and from/to for an arrow; `as: image` returns a PNG crop as base64 (a tile's content, or the canvas region under a drawn object including the tiles and ink inside it). */
    get(params: ObjectGetParams): Promise<ObjectGetResult>;
    /** Create an object. Omit `frame` to let the canvas place it next to the calling agent's terminal (or the viewport center for users). The caller's tile (CANVAS_TILE_ID) becomes createdBy. */
    create(params: ObjectCreateParams): Promise<ObjectCreateResult>;
    /** Patch an object's frame and/or props (shallow merge). Pass `rev` for optimistic concurrency. */
    update(params: ObjectUpdateParams): Promise<ObjectUpdateResult>;
    /** Delete an object (and remove it from any staged mentions). Arrows bound to it keep their drawn route: that end becomes a free `point` where it last attached. */
    delete(params: ObjectDeleteParams): Promise<ObjectDeleteResult>;
  };
  tray: {
    /** Staged mentions, in staging order. */
    list(params?: TrayListParams): Promise<TrayListResult>;
    /** Stage a mention (normally done by the user with Hyper-click; exposed for tests and agents). */
    stage(params: TrayStageParams): Promise<TrayStageResult>;
    /** Remove one staged mention. */
    unstage(params: TrayUnstageParams): Promise<TrayUnstageResult>;
    /** Resolve all staged mentions at their current revision and return them with a ready-to-inject context block. By default the tray is cleared; with `peek: true` it is left intact so the caller can `tray.commit` exactly these ids once the context has really been delivered (a cancelled prompt then loses nothing). */
    drain(params?: TrayDrainParams): Promise<TrayDrainResult>;
    /** Remove exactly these mentions from the tray after their context was delivered (second half of a `peek` drain). Unknown ids are ignored. */
    commit(params: TrayCommitParams): Promise<TrayCommitResult>;
  };
  agent: {
    /** Report lifecycle state for the agent running in a terminal tile. Stale `seq` values from the same source are ignored. */
    report(params: AgentReportParams): Promise<AgentReportResult>;
    /** Report the agent's native session identity so the tile can resume it after a reboot. */
    report_session(params: AgentReportSessionParams): Promise<AgentReportSessionResult>;
    /** The agent in this tile exited; clear its lifecycle authority. */
    release(params: AgentReleaseParams): Promise<AgentReleaseResult>;
    /** Agents across all open boards. */
    list(params?: AgentListParams): Promise<AgentListResult>;
    /** Paste a prompt into another agent's terminal (bracketed paste) and press Enter. Rejected with `conflict` if that agent is blocked. */
    prompt(params: AgentPromptParams): Promise<AgentPromptResult>;
    /** Wait until the target agent reaches one of the given states. */
    wait(params: AgentWaitParams): Promise<AgentWaitResult>;
    /** Recent text of an agent's terminal: the tail of its zmx session scrollback as plain text (what the screen shows plus history), trailing blank lines removed. */
    read(params: AgentReadParams): Promise<AgentReadResult>;
  };
  follow: {
    /** Report a file location an agent just read or edited; re-aims that terminal's follow tile. */
    report(params: FollowReportParams): Promise<FollowReportResult>;
  };
  view: {
    /** Raise an attention marker pointing at an object. Never moves the user's viewport. */
    attention(params: ViewAttentionParams): Promise<ViewAttentionResult>;
    /** PNG of the board's window as the user sees it right now (viewport, tiles, tray). Terminal tiles are drawn from their session text. */
    snapshot(params?: ViewSnapshotParams): Promise<ViewSnapshotResult>;
  };
  events: {
    /** Turn this connection into an event stream. Events: object.created, object.updated, object.deleted, tray.changed, agent.lifecycle, follow.updated. */
    subscribe(params?: EventsSubscribeParams): Promise<EventsSubscribeResult>;
  };
}

export const ENV_DEFAULTS: Record<string, string> = {"caller":"CANVAS_TILE_ID","board":"CANVAS_BOARD_ID"};

export function withEnv<T extends object>(params: T, keys: string[]): T {
  const filled: Record<string, unknown> = { ...params };
  for (const k of keys) {
    const v = process.env[ENV_DEFAULTS[k]];
    if (filled[k] === undefined && v) filled[k] = v;
  }
  return filled as T;
}

export function bindMethods(call: (method: string, params: object) => Promise<unknown>): CanvasApi {
  return {
    system: {
      ping: (params?: SystemPingParams) => call("system.ping", withEnv(params ?? {}, [])) as Promise<SystemPingResult>,
    },
    board: {
      get: (params?: BoardGetParams) => call("board.get", withEnv(params ?? {}, ["board"])) as Promise<BoardGetResult>,
      list: (params?: BoardListParams) => call("board.list", withEnv(params ?? {}, [])) as Promise<BoardListResult>,
      export: (params?: BoardExportParams) => call("board.export", withEnv(params ?? {}, ["board"])) as Promise<BoardExportResult>,
    },
    object: {
      get: (params: ObjectGetParams) => call("object.get", withEnv(params ?? {}, [])) as Promise<ObjectGetResult>,
      create: (params: ObjectCreateParams) => call("object.create", withEnv(params ?? {}, ["board","caller"])) as Promise<ObjectCreateResult>,
      update: (params: ObjectUpdateParams) => call("object.update", withEnv(params ?? {}, ["caller"])) as Promise<ObjectUpdateResult>,
      delete: (params: ObjectDeleteParams) => call("object.delete", withEnv(params ?? {}, ["caller"])) as Promise<ObjectDeleteResult>,
    },
    tray: {
      list: (params?: TrayListParams) => call("tray.list", withEnv(params ?? {}, ["board"])) as Promise<TrayListResult>,
      stage: (params: TrayStageParams) => call("tray.stage", withEnv(params ?? {}, ["board"])) as Promise<TrayStageResult>,
      unstage: (params: TrayUnstageParams) => call("tray.unstage", withEnv(params ?? {}, [])) as Promise<TrayUnstageResult>,
      drain: (params?: TrayDrainParams) => call("tray.drain", withEnv(params ?? {}, ["board","caller"])) as Promise<TrayDrainResult>,
      commit: (params: TrayCommitParams) => call("tray.commit", withEnv(params ?? {}, ["board"])) as Promise<TrayCommitResult>,
    },
    agent: {
      report: (params: AgentReportParams) => call("agent.report", withEnv(params ?? {}, [])) as Promise<AgentReportResult>,
      report_session: (params: AgentReportSessionParams) => call("agent.report_session", withEnv(params ?? {}, [])) as Promise<AgentReportSessionResult>,
      release: (params: AgentReleaseParams) => call("agent.release", withEnv(params ?? {}, [])) as Promise<AgentReleaseResult>,
      list: (params?: AgentListParams) => call("agent.list", withEnv(params ?? {}, [])) as Promise<AgentListResult>,
      prompt: (params: AgentPromptParams) => call("agent.prompt", withEnv(params ?? {}, [])) as Promise<AgentPromptResult>,
      wait: (params: AgentWaitParams) => call("agent.wait", withEnv(params ?? {}, [])) as Promise<AgentWaitResult>,
      read: (params: AgentReadParams) => call("agent.read", withEnv(params ?? {}, [])) as Promise<AgentReadResult>,
    },
    follow: {
      report: (params: FollowReportParams) => call("follow.report", withEnv(params ?? {}, [])) as Promise<FollowReportResult>,
    },
    view: {
      attention: (params: ViewAttentionParams) => call("view.attention", withEnv(params ?? {}, [])) as Promise<ViewAttentionResult>,
      snapshot: (params?: ViewSnapshotParams) => call("view.snapshot", withEnv(params ?? {}, ["board"])) as Promise<ViewSnapshotResult>,
    },
    events: {
      subscribe: (params?: EventsSubscribeParams) => call("events.subscribe", withEnv(params ?? {}, ["board"])) as Promise<EventsSubscribeResult>,
    },
  };
}

export const METHODS = ["system.ping","board.get","board.list","board.export","object.get","object.create","object.update","object.delete","tray.list","tray.stage","tray.unstage","tray.drain","tray.commit","agent.report","agent.report_session","agent.release","agent.list","agent.prompt","agent.wait","agent.read","follow.report","view.attention","view.snapshot","events.subscribe"] as const;
