#!/usr/bin/env bun
// Generates typed clients (and the app's param table) from schema/canvas-api.json, and sets the
// clients' and the Claude Code plugin's package versions to VERSION.
//   bun scripts/gen-clients.ts          write generated files
//   bun scripts/gen-clients.ts --check  exit 1 if generated files are stale
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

type Schema = {
  type?: string | string[];
  $ref?: string;
  const?: unknown;
  enum?: unknown[];
  oneOf?: Schema[];
  properties?: Record<string, Schema>;
  required?: string[];
  items?: Schema;
  description?: string;
  default?: unknown;
};

// `resend`: a read the clients re-send after the connection drops mid-call (see RESEND_METHODS).
type Method = { description: string; params: Schema; result: Schema; resend?: boolean };
type Catalog = { version: number; definitions: Record<string, Schema>; methods: Record<string, Method> };

const root = join(import.meta.dir, "..");
const catalog: Catalog = JSON.parse(readFileSync(join(root, "schema/canvas-api.json"), "utf8"));
const HEADER = "Generated by scripts/gen-clients.ts from schema/canvas-api.json. Do not edit.";

// Params the clients fill from their own tile/board (explicit, else the terminal-tile
// environment) when omitted. Generated methods pass these keys to the client's call.
const ENV_DEFAULTS: Record<string, string> = { caller: "CANVAS_TILE_ID", board: "CANVAS_BOARD_ID" };

// Reads whose reply may be lost to an app restart and that are safe to send again.
const RESEND_METHODS = Object.entries(catalog.methods).filter(([, m]) => m.resend).map(([name]) => name);

const refName = (ref: string) => ref.replace("#/definitions/", "");
const pascal = (s: string) => s.replace(/(^|[._])([a-z])/g, (_, __, c: string) => c.toUpperCase());

// ---------- TypeScript ----------

function tsType(s: Schema, indent = ""): string {
  if (s.$ref) return refName(s.$ref);
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (s.oneOf) return s.oneOf.map((o) => tsType(o, indent)).join(" | ");
  switch (s.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "array": {
      const item = tsType(s.items ?? {}, indent);
      return `${item.includes(" | ") ? `(${item})` : item}[]`;
    }
    case "object": {
      const props = s.properties ?? {};
      const keys = Object.keys(props);
      if (keys.length === 0) return "Record<string, unknown>";
      const req = new Set(s.required ?? []);
      const inner = indent + "  ";
      const lines = keys.map((k) => {
        const doc = props[k].description ? `${inner}/** ${props[k].description} */\n` : "";
        return `${doc}${inner}${k}${req.has(k) ? "" : "?"}: ${tsType(props[k], inner)};`;
      });
      return `{\n${lines.join("\n")}\n${indent}}`;
    }
    default:
      return "unknown";
  }
}

function genTs(): string {
  const out: string[] = [`// ${HEADER}`, "", `export const SCHEMA_VERSION = ${catalog.version};`, ""];
  for (const [name, def] of Object.entries(catalog.definitions)) {
    if (def.description) out.push(`/** ${def.description} */`);
    out.push(`export type ${name} = ${tsType(def)};`, "");
  }
  const namespaces = new Map<string, { types: string[]; bodies: string[] }>();
  for (const [method, m] of Object.entries(catalog.methods)) {
    const P = `${pascal(method)}Params`;
    const R = `${pascal(method)}Result`;
    out.push(`export type ${P} = ${tsType(m.params)};`);
    out.push(`export type ${R} = ${tsType(m.result)};`, "");
    const [ns, fn] = method.split(".");
    const envKeys = Object.keys(m.params.properties ?? {}).filter((k) => k in ENV_DEFAULTS);
    const optional = (m.params.required ?? []).length === 0 ? "?" : "";
    const entry = namespaces.get(ns) ?? { types: [], bodies: [] };
    entry.types.push(`    /** ${m.description} */`, `    ${fn}(params${optional}: ${P}): Promise<${R}>;`);
    entry.bodies.push(`      ${fn}: (params${optional}: ${P}) => call(${JSON.stringify(method)}, params ?? {}, ${JSON.stringify(envKeys)}) as Promise<${R}>,`);
    namespaces.set(ns, entry);
  }
  out.push("/** Every API method, grouped by namespace (`api.board.get(...)`). */");
  out.push("export interface CanvasApi {");
  for (const [ns, { types }] of namespaces) out.push(`  ${ns}: {`, ...types, "  };");
  out.push("}", "");
  out.push("/** Params a client fills from its tile (`caller`) and board when the call omits them, with the env var each defaults from. */");
  out.push(`export const ENV_DEFAULTS: Record<string, string> = ${JSON.stringify(ENV_DEFAULTS)};`, "");
  out.push("/** `call` receives the method's auto-filled param names (keys of ENV_DEFAULTS it accepts). */");
  out.push("export function bindMethods(call: (method: string, params: object, envKeys: string[]) => Promise<unknown>): CanvasApi {");
  out.push("  return {");
  for (const [ns, { bodies }] of namespaces) out.push(`    ${ns}: {`, ...bodies, "    },");
  out.push("  };", "}", "");
  out.push(`export const METHODS = ${JSON.stringify(Object.keys(catalog.methods))} as const;`, "");
  out.push("/** Reads the client re-sends when the connection drops after sending (the app restarted), with `timeoutMs` reduced by the time already spent. */");
  out.push(`export const RESEND_METHODS: readonly string[] = ${JSON.stringify(RESEND_METHODS)};`, "");
  return out.join("\n");
}

// ---------- Python ----------

// Python keywords (not builtins like `id`/`type`, which are fine as parameter names).
const PY_KEYWORDS: Record<string, true> = Object.fromEntries(
  ["as", "from", "import", "class", "def", "return", "in", "is", "not", "and", "or", "global", "lambda", "pass", "raise", "try", "while", "with", "yield", "del", "for", "if", "else", "elif", "except", "finally", "assert", "break", "continue", "nonlocal", "async", "await", "None", "True", "False"].map((k) => [k, true]),
);
const pyName = (k: string) => (PY_KEYWORDS[k] ? `${k}_` : k);
const snake = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();

function pyType(s: Schema): string {
  if (s.$ref) return `"${refName(s.$ref)}"`;
  if (s.const !== undefined) return `Literal[${JSON.stringify(s.const)}]`;
  if (s.enum) return `Literal[${s.enum.map((v) => JSON.stringify(v)).join(", ")}]`;
  if (s.oneOf) return `Union[${s.oneOf.map(pyType).join(", ")}]`;
  switch (s.type) {
    case "string":
      return "str";
    case "number":
      return "float";
    case "integer":
      return "int";
    case "boolean":
      return "bool";
    case "array":
      return `list[${pyType(s.items ?? {})}]`;
    case "object":
      return "dict[str, Any]";
    default:
      return "Any";
  }
}

function pyTypedDict(name: string, s: Schema): string[] {
  const props = s.properties ?? {};
  const req = new Set(s.required ?? []);
  const lines = [`class ${name}(TypedDict):`];
  if (s.description) lines.push(`    """${s.description}"""`);
  const keys = Object.keys(props);
  if (keys.length === 0) lines.push("    pass");
  for (const k of keys) {
    const t = pyType(props[k]);
    lines.push(`    ${k}: ${req.has(k) ? `Required[${t}]` : `NotRequired[${t}]`}`);
  }
  return lines;
}

function genPy(): string {
  const out: string[] = [
    `"""${HEADER}"""`,
    "",
    "from __future__ import annotations",
    "",
    "import functools",
    "import inspect",
    "import re",
    "from typing import Any, Callable, Literal, NotRequired, Required, TypedDict, TypeVar, Union",
    "",
    `SCHEMA_VERSION = ${catalog.version}`,
    `ENV_DEFAULTS = ${JSON.stringify(ENV_DEFAULTS)}`,
    "",
    '_Api = TypeVar("_Api")',
    "",
    "",
    "def _snake_case_hints(cls: type[_Api]) -> type[_Api]:",
    '    """A keyword spelled the wire\'s camelCase way (`timeoutMs`, as `canvas methods` prints it) fails naming the snake_case parameter."""',
    "    for name, method in list(vars(cls).items()):",
    '        if name.startswith("_") or not callable(method):',
    "            continue",
    "        accepted = set(inspect.signature(method).parameters)",
    "",
    "        def hinted(method: Callable[..., Any] = method, accepted: set[str] = accepted) -> Callable[..., Any]:",
    "            @functools.wraps(method)",
    "            def call(self: Any, *args: Any, **kwargs: Any) -> Any:",
    "                for key in kwargs:",
    '                    snake = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\\1", key).lower()',
    '                    for hint in (snake, snake + "_"):',
    "                        if key not in accepted and hint in accepted:",
    "                            raise TypeError(f\"{method.__qualname__}() got an unexpected keyword argument '{key}'; the Python SDK spells it '{hint}'\")",
    "                return method(self, *args, **kwargs)",
    "",
    "            return call",
    "",
    "        setattr(cls, name, hinted())",
    "    return cls",
    "",
    "",
  ];
  // TypedDicts whose field names are Python keywords (e.g. "from") use the functional syntax.
  for (const [name, def] of Object.entries(catalog.definitions)) {
    const isObject = def.type === "object" && def.properties;
    if (isObject && Object.keys(def.properties!).some((k) => PY_KEYWORDS[k])) {
      const req = new Set(def.required ?? []);
      const fields = Object.entries(def.properties!).map(([k, v]) => `"${k}": ${req.has(k) ? `Required[${pyType(v)}]` : `NotRequired[${pyType(v)}]`}`);
      out.push(`${name} = TypedDict("${name}", {${fields.join(", ")}})`, "");
    } else if (isObject) {
      out.push(...pyTypedDict(name, def), "");
    } else {
      out.push(`${name} = ${pyType(def)}`, "");
    }
  }
  const namespaces = new Map<string, string[]>();
  for (const [method, m] of Object.entries(catalog.methods)) {
    const [ns, fn] = method.split(".");
    const props = m.params.properties ?? {};
    const req = new Set(m.params.required ?? []);
    const args = Object.keys(props)
      .sort((a, b) => Number(req.has(b)) - Number(req.has(a)))
      .map((k) => `${pyName(snake(k))}: ${pyType(props[k])}${req.has(k) ? "" : " | None = None"}`);
    const mapping = Object.keys(props).map((k) => `"${k}": ${pyName(snake(k))}`);
    const envKeys = Object.keys(props).filter((k) => k in ENV_DEFAULTS);
    const lines = [
      `    def ${pyName(fn)}(self${args.length ? ", *, " + args.join(", ") : ""}) -> dict[str, Any]:`,
      `        """${m.description}"""`,
      `        params = {${mapping.join(", ")}}`,
      `        return self._call(${JSON.stringify(method)}, params, ${JSON.stringify(envKeys)})`,
      "",
    ];
    namespaces.set(ns, [...(namespaces.get(ns) ?? []), ...lines]);
  }
  // The client drops None values and fills the env keys from its own tile/board.
  const callType = "Callable[[str, dict[str, Any], list[str]], Any]";
  for (const [ns, lines] of namespaces) {
    out.push("@_snake_case_hints", `class ${pascal(ns)}Api:`, `    def __init__(self, call: ${callType}) -> None:`, "        self._call = call", "", ...lines);
  }
  out.push("class GeneratedApi:", `    def __init__(self, call: ${callType}) -> None:`);
  for (const ns of namespaces.keys()) out.push(`        self.${pyName(ns)} = ${pascal(ns)}Api(call)`);
  out.push("", `METHODS = ${JSON.stringify(Object.keys(catalog.methods))}`, "");
  out.push("# Reads the client re-sends when the connection drops after sending (the app restarted), with `timeoutMs` reduced by the time already spent.");
  out.push(`RESEND_METHODS = ${JSON.stringify(RESEND_METHODS)}`, "");
  return out.join("\n");
}

// ---------- Swift (the app's param check) ----------

function genSwift(): string {
  const list = (keys: string[]) => `[${keys.map((k) => JSON.stringify(k)).join(", ")}]`;
  const out: string[] = [`// ${HEADER}`, "", "/// Each method's params (`params.properties`, in schema order) and the required ones: what"];
  out.push("/// `ApiRouter` checks every request against, and names in its `invalid_params` errors.");
  out.push("enum ApiParams {", "    static let methods: [String: (accepted: [String], required: [String])] = [");
  for (const [method, m] of Object.entries(catalog.methods)) {
    out.push(`        ${JSON.stringify(method)}: (${list(Object.keys(m.params.properties ?? {}))}, ${list(m.params.required ?? [])}),`);
  }
  out.push("    ]", "}", "");
  return out.join("\n");
}

// ---------- Package versions (from VERSION, which scripts/bundle.sh also reads) ----------

const version = readFileSync(join(root, "VERSION"), "utf8").trim();
if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`VERSION must be MAJOR.MINOR.PATCH, not ${JSON.stringify(version)}`);

/** `file` with its first match of `pattern` (whose one group is the version) set to VERSION. */
function withVersion(rel: string, pattern: RegExp): string {
  const current = readFileSync(join(root, rel), "utf8");
  if (!pattern.test(current)) throw new Error(`no version in ${rel}`);
  return current.replace(pattern, (whole, old: string) => whole.replace(old, version));
}

const targets: Array<[string, string]> = [
  ["clients/ts/src/generated.ts", genTs()],
  ["clients/python/canvas_sdk/_generated.py", genPy()],
  ["Sources/CanvasCore/ApiParams.swift", genSwift()],
  ["clients/python/pyproject.toml", withVersion("clients/python/pyproject.toml", /^version = "([^"]+)"$/m)],
  ["clients/ts/package.json", withVersion("clients/ts/package.json", /^  "version": "([^"]+)",$/m)],
  ["extensions/claude/.claude-plugin/plugin.json", withVersion("extensions/claude/.claude-plugin/plugin.json", /^  "version": "([^"]+)",$/m)],
];

const check = process.argv.includes("--check");
let stale = false;
for (const [rel, content] of targets) {
  const path = join(root, rel);
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (current === content) continue;
  if (check) {
    console.error(`stale: ${rel}`);
    stale = true;
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${rel}`);
  }
}
if (stale) process.exit(1);
