"""Generated by scripts/gen-clients.ts from schema/canvas-api.json. Do not edit."""

from __future__ import annotations

import os
from typing import Any, Callable, Literal, NotRequired, Required, TypedDict, Union

SCHEMA_VERSION = 1
ENV_DEFAULTS = {"caller":"CANVAS_TILE_ID","board":"CANVAS_BOARD_ID"}

Id = str

class Frame(TypedDict):
    x: Required[float]
    y: Required[float]
    w: Required[float]
    h: Required[float]

Actor = Union[dict[str, Any], dict[str, Any]]

class LineRange(TypedDict):
    """1-based inclusive line range"""
    start: Required[int]
    end: Required[int]

class Lifecycle(TypedDict):
    state: Required[Literal["working", "blocked", "idle", "done", "unknown"]]
    message: NotRequired[str]
    seen: NotRequired[bool]

class TerminalProps(TypedDict):
    cwd: Required[str]
    command: Required[list[str]]
    zmxSession: NotRequired[str]
    title: NotRequired[str]
    agent: NotRequired[dict[str, Any]]
    lifecycle: NotRequired["Lifecycle"]

class BrowserProps(TypedDict):
    url: Required[str]
    title: NotRequired[str]

class CodeProps(TypedDict):
    path: Required[str]
    range: NotRequired["LineRange"]
    symbol: NotRequired[str]
    mode: NotRequired[Literal["diff", "source"]]
    diffBase: NotRequired[str]
    followOf: NotRequired["Id"]
    pinnedCommit: NotRequired[str]

class NoteProps(TypedDict):
    markdown: Required[str]

class HtmlProps(TypedDict):
    html: Required[str]
    title: NotRequired[str]
    allowNetwork: NotRequired[list[str]]
    state: NotRequired[dict[str, Any]]

class ShapeProps(TypedDict):
    kind: Required[Literal["rect", "ellipse", "text", "ink"]]
    text: NotRequired[str]
    points: NotRequired[list[list[float]]]
    color: NotRequired[str]

Binding = Union[dict[str, Any], dict[str, Any]]

ArrowProps = TypedDict("ArrowProps", {"from": Required["Binding"], "to": Required["Binding"], "relation": NotRequired[str], "label": NotRequired[str]})

class GroupProps(TypedDict):
    name: NotRequired[str]
    members: Required[list["Id"]]

ObjectType = Literal["terminal", "browser", "code", "note", "html", "shape", "arrow", "group"]

class CanvasObject(TypedDict):
    id: Required["Id"]
    type: Required["ObjectType"]
    frame: Required["Frame"]
    z: Required[float]
    rev: Required[int]
    parent: NotRequired["Id"]
    createdBy: Required["Actor"]
    updatedBy: NotRequired["Actor"]
    createdAt: Required[str]
    updatedAt: Required[str]
    props: Required[dict[str, Any]]

MentionTarget = Union[dict[str, Any], dict[str, Any], dict[str, Any], dict[str, Any], dict[str, Any]]

class Mention(TypedDict):
    id: Required["Id"]
    target: Required["MentionTarget"]
    label: Required[str]
    stagedAt: Required[str]
    edited: Required[bool]

class ResolvedMention(TypedDict):
    id: Required["Id"]
    ref: Required[str]
    label: Required[str]
    summary: Required[str]
    graph: NotRequired[dict[str, Any]]

class Agent(TypedDict):
    tile: Required["Id"]
    board: NotRequired["Id"]
    name: NotRequired[str]
    kind: Required[str]
    sessionId: NotRequired[str]
    lifecycle: Required["Lifecycle"]

class BoardInfo(TypedDict):
    board: Required["Id"]
    root: Required[str]
    archived: Required[bool]
    open: Required[bool]
    updatedAt: NotRequired[str]
    objects: Required[int]

def _with_env(params: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    for k in keys:
        if params.get(k) is None and os.environ.get(ENV_DEFAULTS[k]):
            params[k] = os.environ[ENV_DEFAULTS[k]]
    return {k: v for k, v in params.items() if v is not None}

class SystemApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self._call = call

    def ping(self) -> dict[str, Any]:
        """Liveness and schema version."""
        params = {}
        return self._call("system.ping", _with_env(params, []))

class BoardApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self._call = call

    def get(self, *, board: "Id" | None = None, since: int | None = None) -> dict[str, Any]:
        """Board manifest: all objects (props summarized for heavy types) plus a change cursor. Objects created or changed since `since` are flagged."""
        params = {"board": board, "since": since}
        return self._call("board.get", _with_env(params, ["board"]))

    def list(self) -> dict[str, Any]:
        """Every stored board, open or not, including archived boards whose root directory is gone."""
        params = {}
        return self._call("board.list", _with_env(params, []))

    def export(self, *, board: "Id" | None = None, path: str | None = None) -> dict[str, Any]:
        """Write a pretty-printed JSON snapshot of an open board (objects, frames, props; not the personal selection tray) into the repo. Committing it is left to the caller."""
        params = {"board": board, "path": path}
        return self._call("board.export", _with_env(params, ["board"]))

class ObjectApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self._call = call

    def get(self, *, id: "Id", as_: Literal["raw", "graph", "image"] | None = None) -> dict[str, Any]:
        """Read one object. `as: graph` adds structural relations (encloses, overlaps, arrows in/out); `as: image` returns a PNG crop as base64."""
        params = {"id": id, "as": as_}
        return self._call("object.get", _with_env(params, []))

    def create(self, *, type: "ObjectType", props: dict[str, Any], board: "Id" | None = None, frame: "Frame" | None = None, parent: "Id" | None = None, caller: "Id" | None = None) -> dict[str, Any]:
        """Create an object. Omit `frame` to let the canvas place it next to the calling agent's terminal (or the viewport center for users). The caller's tile (CANVAS_TILE_ID) becomes createdBy."""
        params = {"board": board, "type": type, "props": props, "frame": frame, "parent": parent, "caller": caller}
        return self._call("object.create", _with_env(params, ["board","caller"]))

    def update(self, *, id: "Id", rev: int | None = None, frame: "Frame" | None = None, props: dict[str, Any] | None = None, caller: "Id" | None = None) -> dict[str, Any]:
        """Patch an object's frame and/or props (shallow merge). Pass `rev` for optimistic concurrency."""
        params = {"id": id, "rev": rev, "frame": frame, "props": props, "caller": caller}
        return self._call("object.update", _with_env(params, ["caller"]))

    def delete(self, *, id: "Id", caller: "Id" | None = None) -> dict[str, Any]:
        """Delete an object (and remove it from any staged mentions)."""
        params = {"id": id, "caller": caller}
        return self._call("object.delete", _with_env(params, ["caller"]))

class TrayApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self._call = call

    def list(self, *, board: "Id" | None = None) -> dict[str, Any]:
        """Staged mentions, in staging order."""
        params = {"board": board}
        return self._call("tray.list", _with_env(params, ["board"]))

    def stage(self, *, target: "MentionTarget", board: "Id" | None = None) -> dict[str, Any]:
        """Stage a mention (normally done by the user with Hyper-click; exposed for tests and agents)."""
        params = {"target": target, "board": board}
        return self._call("tray.stage", _with_env(params, ["board"]))

    def unstage(self, *, id: "Id") -> dict[str, Any]:
        """Remove one staged mention."""
        params = {"id": id}
        return self._call("tray.unstage", _with_env(params, []))

    def drain(self, *, board: "Id" | None = None, caller: "Id" | None = None, peek: bool | None = None) -> dict[str, Any]:
        """Resolve all staged mentions at their current revision and return them with a ready-to-inject context block. By default the tray is cleared; with `peek: true` it is left intact so the caller can `tray.commit` exactly these ids once the context has really been delivered (a cancelled prompt then loses nothing)."""
        params = {"board": board, "caller": caller, "peek": peek}
        return self._call("tray.drain", _with_env(params, ["board","caller"]))

    def commit(self, *, ids: list["Id"], board: "Id" | None = None) -> dict[str, Any]:
        """Remove exactly these mentions from the tray after their context was delivered (second half of a `peek` drain). Unknown ids are ignored."""
        params = {"board": board, "ids": ids}
        return self._call("tray.commit", _with_env(params, ["board"]))

class AgentApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self._call = call

    def report(self, *, tile: "Id", kind: str, state: Literal["working", "blocked", "idle", "unknown"], message: str | None = None, seq: int | None = None, source: str | None = None) -> dict[str, Any]:
        """Report lifecycle state for the agent running in a terminal tile. Stale `seq` values from the same source are ignored."""
        params = {"tile": tile, "kind": kind, "state": state, "message": message, "seq": seq, "source": source}
        return self._call("agent.report", _with_env(params, []))

    def report_session(self, *, tile: "Id", kind: str, session_id: str | None = None, session_path: str | None = None) -> dict[str, Any]:
        """Report the agent's native session identity so the tile can resume it after a reboot."""
        params = {"tile": tile, "kind": kind, "sessionId": session_id, "sessionPath": session_path}
        return self._call("agent.report_session", _with_env(params, []))

    def release(self, *, tile: "Id", kind: str, source: str | None = None) -> dict[str, Any]:
        """The agent in this tile exited; clear its lifecycle authority."""
        params = {"tile": tile, "kind": kind, "source": source}
        return self._call("agent.release", _with_env(params, []))

    def list(self) -> dict[str, Any]:
        """Agents across all open boards."""
        params = {}
        return self._call("agent.list", _with_env(params, []))

    def prompt(self, *, target: str, text: str) -> dict[str, Any]:
        """Paste a prompt into another agent's terminal (bracketed paste) and press Enter. Rejected with `conflict` if that agent is blocked."""
        params = {"target": target, "text": text}
        return self._call("agent.prompt", _with_env(params, []))

    def wait(self, *, target: str, until: list[Literal["working", "blocked", "idle", "done", "unknown"]] | None = None, timeout_ms: int | None = None) -> dict[str, Any]:
        """Wait until the target agent reaches one of the given states."""
        params = {"target": target, "until": until, "timeoutMs": timeout_ms}
        return self._call("agent.wait", _with_env(params, []))

    def read(self, *, target: str, lines: int | None = None) -> dict[str, Any]:
        """Recent text of an agent's terminal: the tail of its zmx session scrollback as plain text (what the screen shows plus history), trailing blank lines removed."""
        params = {"target": target, "lines": lines}
        return self._call("agent.read", _with_env(params, []))

class FollowApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self._call = call

    def report(self, *, tile: "Id", path: str, action: Literal["read", "edit", "lsp", "search"], range: "LineRange" | None = None) -> dict[str, Any]:
        """Report a file location an agent just read or edited; re-aims that terminal's follow tile."""
        params = {"tile": tile, "path": path, "range": range, "action": action}
        return self._call("follow.report", _with_env(params, []))

class ViewApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self._call = call

    def attention(self, *, id: "Id", message: str | None = None) -> dict[str, Any]:
        """Raise an attention marker pointing at an object. Never moves the user's viewport."""
        params = {"id": id, "message": message}
        return self._call("view.attention", _with_env(params, []))

    def snapshot(self, *, board: "Id" | None = None) -> dict[str, Any]:
        """PNG of the board's window as the user sees it right now (viewport, tiles, tray). Terminal tiles are drawn from their session text."""
        params = {"board": board}
        return self._call("view.snapshot", _with_env(params, ["board"]))

class EventsApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self._call = call

    def subscribe(self, *, board: "Id" | None = None, events: list[str] | None = None) -> dict[str, Any]:
        """Turn this connection into an event stream. Events: object.created, object.updated, object.deleted, tray.changed, agent.lifecycle, follow.updated."""
        params = {"board": board, "events": events}
        return self._call("events.subscribe", _with_env(params, ["board"]))

class GeneratedApi:
    def __init__(self, call: Callable[[str, dict[str, Any]], Any]) -> None:
        self.system = SystemApi(call)
        self.board = BoardApi(call)
        self.object = ObjectApi(call)
        self.tray = TrayApi(call)
        self.agent = AgentApi(call)
        self.follow = FollowApi(call)
        self.view = ViewApi(call)
        self.events = EventsApi(call)

METHODS = ["system.ping","board.get","board.list","board.export","object.get","object.create","object.update","object.delete","tray.list","tray.stage","tray.unstage","tray.drain","tray.commit","agent.report","agent.report_session","agent.release","agent.list","agent.prompt","agent.wait","agent.read","follow.report","view.attention","view.snapshot","events.subscribe"]
